### PR TITLE
Add code to include arbitrary extra `x-amz-` headers

### PR DESCRIPTION
**Pull request by badslug**
Attempt to add other amazon headers to the auth signature

### CODE REVIEW

**Comment by badslug** [comment]
@robbiehanson sorry this took so long - if you have the time can you see if this version works for your use-case? This patch should fix #4. It will take me even longer to set up tests against S3 so if you can verify this works for you I'll add it to the shipping version. Thanks.

**Comment by badslug** [comment]
I'm going to assume this works (or at least doesn't make things worse)...

**Comment by fmasuhr** [comment]
@badslug This implementation is actually not worker properly. The usage of `request.getHeaderNames()` is creating a self-dependency. This is detected by Paw and creates warnings:

bildschirmfoto 2017-04-26 um 15 15 14

**Comment by JonathanMontane** [comment]
@fmasuhr (Paw Team here) This is actually trickier than it looks like to fix, and I'll see how to fix this early tomorrow morning. In the meantime, we can rollback the extension to a previous version if you feel that is preferable.

**Comment by fmasuhr** [comment]
@JonathanMontane Thank you for your fast response. Actually the extensions is currently broken anyway as there are typos in there. I already prepared a fix here https://github.com/badslug/Paw-AWSSignature4DynamicValue/pull/11 which would fix the extension to work again in Paw.

For me it is fine for now getting the warning. As you pointed out there is the need for a more complex refactoring and i can wait till this is done

**Pull request merged**
